
[build]
  publish = "build"

  command = "npm run build'"

[[headers]]
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

    cache-control = '''
    public,
    max-age=31556926'''